from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Set


class AwsProviderError(RuntimeError):
    def __init__(self, message: str, returncode: int = 1, detail: str = "") -> None:
        super().__init__(message)
        self.returncode = returncode
        self.detail = detail


class AwsProvider(Protocol):
    def capabilities(self) -> Set[str]: ...

    def read(self, operation: str, **parameters: Any) -> Dict[str, Any]: ...

    def caller_identity(self) -> Dict[str, Any]: ...

    def list_buckets(self) -> List[str]: ...

    def list_log_groups(self) -> List[Dict[str, Any]]: ...

    def list_ebs_volumes(self) -> List[Dict[str, Any]]: ...

    def list_elastic_ips(self) -> List[Dict[str, Any]]: ...

    def get_iam_account_summary(self) -> Dict[str, Any]: ...

    def list_cloudtrail_trails(self) -> List[Dict[str, Any]]: ...

    def list_rds_instances(self) -> List[Dict[str, Any]]: ...

    def list_lambda_functions(self) -> List[Dict[str, Any]]: ...

    def get_public_access_block(self, bucket: str) -> Dict[str, Any]: ...

    def get_bucket_policy(self, bucket: str) -> Optional[Dict[str, Any]]: ...

    def get_bucket_encryption_rules(self, bucket: str) -> List[Dict[str, Any]]: ...

    def get_bucket_lifecycle_rules(self, bucket: str) -> List[Dict[str, Any]]: ...

    def get_bucket_versioning_status(self, bucket: str) -> Optional[str]: ...

    def put_public_access_block(self, bucket: str) -> None: ...

    def put_default_encryption(self, bucket: str) -> None: ...

    def put_lifecycle(
        self,
        bucket: str,
        *,
        transition_days: int = 30,
        storage_class: str = "STANDARD_IA",
    ) -> None: ...

    def put_versioning(self, bucket: str) -> None: ...

    def put_bucket_logging(
        self,
        bucket: str,
        *,
        target_bucket: str,
        target_prefix: str,
    ) -> None: ...

    def enable_alb_access_logging(
        self,
        load_balancer_arn: str,
        *,
        target_bucket: str,
        target_prefix: str,
    ) -> None: ...

    def put_log_retention(self, log_group_name: str, retention_days: int) -> None: ...

    def update_cloudtrail_log_file_validation(self, trail_name: str, *, enabled: bool) -> None: ...
