from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Tuple


@dataclass(frozen=True)
class AwsReadOperation:
    key: str
    service: str
    sdk_operation: str
    cli_command: Tuple[str, ...]
    result_keys: Tuple[str, ...] = ()
    paginated: bool = False
    expected_missing_codes: Tuple[str, ...] = ()


def _op(
    key: str,
    service: str,
    sdk_operation: str,
    *cli_command: str,
    result_keys: Tuple[str, ...] = (),
    paginated: bool = False,
    expected_missing_codes: Tuple[str, ...] = (),
) -> AwsReadOperation:
    return AwsReadOperation(
        key=key,
        service=service,
        sdk_operation=sdk_operation,
        cli_command=tuple(cli_command),
        result_keys=result_keys,
        paginated=paginated,
        expected_missing_codes=expected_missing_codes,
    )


_OPERATIONS = (
    _op("sts.get_caller_identity", "sts", "get_caller_identity", "sts", "get-caller-identity"),
    _op(
        "config.describe_configuration_recorders",
        "config",
        "describe_configuration_recorders",
        "configservice",
        "describe-configuration-recorders",
    ),
    _op(
        "config.describe_configuration_recorder_status",
        "config",
        "describe_configuration_recorder_status",
        "configservice",
        "describe-configuration-recorder-status",
    ),
    _op(
        "config.get_resource_config_history",
        "config",
        "get_resource_config_history",
        "configservice",
        "get-resource-config-history",
        expected_missing_codes=("ResourceNotDiscoveredException",),
    ),
    _op(
        "route53.list_hosted_zones",
        "route53",
        "list_hosted_zones",
        "route53",
        "list-hosted-zones",
        result_keys=("HostedZones",),
        paginated=True,
    ),
    _op(
        "route53.list_resource_record_sets",
        "route53",
        "list_resource_record_sets",
        "route53",
        "list-resource-record-sets",
        result_keys=("ResourceRecordSets",),
        paginated=True,
    ),
    _op(
        "logs.describe_log_groups",
        "logs",
        "describe_log_groups",
        "logs",
        "describe-log-groups",
        result_keys=("logGroups",),
        paginated=True,
    ),
    _op(
        "iam.get_account_password_policy",
        "iam",
        "get_account_password_policy",
        "iam",
        "get-account-password-policy",
        expected_missing_codes=("NoSuchEntity",),
    ),
    _op(
        "iam.get_account_authorization_details",
        "iam",
        "get_account_authorization_details",
        "iam",
        "get-account-authorization-details",
        result_keys=("UserDetailList", "GroupDetailList", "RoleDetailList", "Policies"),
        paginated=True,
    ),
    _op("iam.get_account_summary", "iam", "get_account_summary", "iam", "get-account-summary"),
    _op(
        "iam.list_mfa_devices",
        "iam",
        "list_mfa_devices",
        "iam",
        "list-mfa-devices",
        result_keys=("MFADevices",),
        paginated=True,
    ),
    _op(
        "iam.get_login_profile",
        "iam",
        "get_login_profile",
        "iam",
        "get-login-profile",
        expected_missing_codes=("NoSuchEntity",),
    ),
    _op(
        "iam.list_access_keys",
        "iam",
        "list_access_keys",
        "iam",
        "list-access-keys",
        result_keys=("AccessKeyMetadata",),
        paginated=True,
    ),
    _op("iam.get_policy", "iam", "get_policy", "iam", "get-policy"),
    _op("iam.get_policy_version", "iam", "get_policy_version", "iam", "get-policy-version"),
    _op(
        "iam.list_attached_role_policies",
        "iam",
        "list_attached_role_policies",
        "iam",
        "list-attached-role-policies",
        result_keys=("AttachedPolicies",),
        paginated=True,
    ),
    _op(
        "iam.list_role_policies",
        "iam",
        "list_role_policies",
        "iam",
        "list-role-policies",
        result_keys=("PolicyNames",),
        paginated=True,
    ),
    _op("iam.get_role_policy", "iam", "get_role_policy", "iam", "get-role-policy"),
    _op("iam.get_role", "iam", "get_role", "iam", "get-role"),
    _op(
        "iam.list_roles",
        "iam",
        "list_roles",
        "iam",
        "list-roles",
        result_keys=("Roles",),
        paginated=True,
    ),
    _op(
        "ec2.describe_security_groups",
        "ec2",
        "describe_security_groups",
        "ec2",
        "describe-security-groups",
        result_keys=("SecurityGroups",),
        paginated=True,
    ),
    _op(
        "ec2.describe_network_interfaces",
        "ec2",
        "describe_network_interfaces",
        "ec2",
        "describe-network-interfaces",
        result_keys=("NetworkInterfaces",),
        paginated=True,
    ),
    _op(
        "ec2.describe_volumes",
        "ec2",
        "describe_volumes",
        "ec2",
        "describe-volumes",
        result_keys=("Volumes",),
        paginated=True,
    ),
    _op("ec2.describe_addresses", "ec2", "describe_addresses", "ec2", "describe-addresses"),
    _op(
        "ec2.describe_vpcs",
        "ec2",
        "describe_vpcs",
        "ec2",
        "describe-vpcs",
        result_keys=("Vpcs",),
        paginated=True,
    ),
    _op(
        "ec2.describe_flow_logs",
        "ec2",
        "describe_flow_logs",
        "ec2",
        "describe-flow-logs",
        result_keys=("FlowLogs",),
        paginated=True,
    ),
    _op(
        "ec2.describe_snapshots",
        "ec2",
        "describe_snapshots",
        "ec2",
        "describe-snapshots",
        result_keys=("Snapshots",),
        paginated=True,
    ),
    _op(
        "ec2.describe_images",
        "ec2",
        "describe_images",
        "ec2",
        "describe-images",
        result_keys=("Images",),
    ),
    _op(
        "ec2.describe_instances",
        "ec2",
        "describe_instances",
        "ec2",
        "describe-instances",
        result_keys=("Reservations",),
        paginated=True,
    ),
    _op(
        "ec2.describe_launch_template_versions",
        "ec2",
        "describe_launch_template_versions",
        "ec2",
        "describe-launch-template-versions",
        result_keys=("LaunchTemplateVersions",),
        paginated=True,
    ),
    _op(
        "ec2.describe_launch_templates",
        "ec2",
        "describe_launch_templates",
        "ec2",
        "describe-launch-templates",
        result_keys=("LaunchTemplates",),
        paginated=True,
    ),
    _op("s3.list_buckets", "s3", "list_buckets", "s3api", "list-buckets", result_keys=("Buckets",)),
    _op(
        "s3.get_public_access_block",
        "s3",
        "get_public_access_block",
        "s3api",
        "get-public-access-block",
        expected_missing_codes=("NoSuchPublicAccessBlockConfiguration",),
    ),
    _op(
        "s3.get_bucket_policy",
        "s3",
        "get_bucket_policy",
        "s3api",
        "get-bucket-policy",
        expected_missing_codes=("NoSuchBucketPolicy",),
    ),
    _op(
        "s3.get_bucket_encryption",
        "s3",
        "get_bucket_encryption",
        "s3api",
        "get-bucket-encryption",
        expected_missing_codes=("ServerSideEncryptionConfigurationNotFoundError",),
    ),
    _op(
        "s3.get_bucket_lifecycle_configuration",
        "s3",
        "get_bucket_lifecycle_configuration",
        "s3api",
        "get-bucket-lifecycle-configuration",
        expected_missing_codes=("NoSuchLifecycleConfiguration",),
    ),
    _op("s3.get_bucket_logging", "s3", "get_bucket_logging", "s3api", "get-bucket-logging"),
    _op("s3.get_bucket_location", "s3", "get_bucket_location", "s3api", "get-bucket-location"),
    _op(
        "s3.get_bucket_tagging",
        "s3",
        "get_bucket_tagging",
        "s3api",
        "get-bucket-tagging",
        expected_missing_codes=("NoSuchTagSet",),
    ),
    _op(
        "s3.get_bucket_versioning", "s3", "get_bucket_versioning", "s3api", "get-bucket-versioning"
    ),
    _op(
        "s3.get_object_lock_configuration",
        "s3",
        "get_object_lock_configuration",
        "s3api",
        "get-object-lock-configuration",
        expected_missing_codes=(
            "ObjectLockConfigurationNotFoundError",
            "NoSuchObjectLockConfiguration",
        ),
    ),
    _op(
        "s3.get_bucket_replication",
        "s3",
        "get_bucket_replication",
        "s3api",
        "get-bucket-replication",
        expected_missing_codes=("ReplicationConfigurationNotFoundError",),
    ),
    _op(
        "efs.describe_file_systems",
        "efs",
        "describe_file_systems",
        "efs",
        "describe-file-systems",
        result_keys=("FileSystems",),
        paginated=True,
    ),
    _op(
        "efs.describe_lifecycle_configuration",
        "efs",
        "describe_lifecycle_configuration",
        "efs",
        "describe-lifecycle-configuration",
        expected_missing_codes=("FileSystemNotFound",),
    ),
    _op(
        "efs.describe_mount_targets",
        "efs",
        "describe_mount_targets",
        "efs",
        "describe-mount-targets",
        result_keys=("MountTargets",),
        paginated=True,
    ),
    _op(
        "efs.describe_access_points",
        "efs",
        "describe_access_points",
        "efs",
        "describe-access-points",
        result_keys=("AccessPoints",),
        paginated=True,
    ),
    _op(
        "backup.list_recovery_points_by_resource",
        "backup",
        "list_recovery_points_by_resource",
        "backup",
        "list-recovery-points-by-resource",
        result_keys=("RecoveryPoints",),
        paginated=True,
    ),
    _op(
        "lambda.list_functions",
        "lambda",
        "list_functions",
        "lambda",
        "list-functions",
        result_keys=("Functions",),
        paginated=True,
    ),
    _op(
        "lambda.get_function_configuration",
        "lambda",
        "get_function_configuration",
        "lambda",
        "get-function-configuration",
        expected_missing_codes=("ResourceNotFoundException",),
    ),
    _op("lambda.list_tags", "lambda", "list_tags", "lambda", "list-tags"),
    _op(
        "lambda.list_event_source_mappings",
        "lambda",
        "list_event_source_mappings",
        "lambda",
        "list-event-source-mappings",
        result_keys=("EventSourceMappings",),
        paginated=True,
    ),
    _op(
        "lambda.list_function_url_configs",
        "lambda",
        "list_function_url_configs",
        "lambda",
        "list-function-url-configs",
        result_keys=("FunctionUrlConfigs",),
        paginated=True,
    ),
    _op(
        "lambda.list_aliases",
        "lambda",
        "list_aliases",
        "lambda",
        "list-aliases",
        result_keys=("Aliases",),
        paginated=True,
    ),
    _op(
        "lambda.list_versions_by_function",
        "lambda",
        "list_versions_by_function",
        "lambda",
        "list-versions-by-function",
        result_keys=("Versions",),
        paginated=True,
    ),
    _op(
        "lambda.get_policy",
        "lambda",
        "get_policy",
        "lambda",
        "get-policy",
        expected_missing_codes=("ResourceNotFoundException",),
    ),
    _op(
        "events.list_rule_names_by_target",
        "events",
        "list_rule_names_by_target",
        "events",
        "list-rule-names-by-target",
        result_keys=("RuleNames",),
        paginated=True,
    ),
    _op(
        "lambda.list_provisioned_concurrency_configs",
        "lambda",
        "list_provisioned_concurrency_configs",
        "lambda",
        "list-provisioned-concurrency-configs",
        result_keys=("ProvisionedConcurrencyConfigs",),
        paginated=True,
    ),
    _op(
        "cloudwatch.get_metric_data",
        "cloudwatch",
        "get_metric_data",
        "cloudwatch",
        "get-metric-data",
        result_keys=("MetricDataResults",),
        paginated=True,
    ),
    _op(
        "cloudtrail.describe_trails",
        "cloudtrail",
        "describe_trails",
        "cloudtrail",
        "describe-trails",
    ),
    _op(
        "cloudtrail.get_trail_status",
        "cloudtrail",
        "get_trail_status",
        "cloudtrail",
        "get-trail-status",
    ),
    _op(
        "rds.describe_db_instances",
        "rds",
        "describe_db_instances",
        "rds",
        "describe-db-instances",
        result_keys=("DBInstances",),
        paginated=True,
    ),
    _op(
        "rds.describe_db_snapshots",
        "rds",
        "describe_db_snapshots",
        "rds",
        "describe-db-snapshots",
        result_keys=("DBSnapshots",),
        paginated=True,
    ),
    _op(
        "dynamodb.list_tables",
        "dynamodb",
        "list_tables",
        "dynamodb",
        "list-tables",
        result_keys=("TableNames",),
        paginated=True,
    ),
    _op("dynamodb.describe_table", "dynamodb", "describe_table", "dynamodb", "describe-table"),
    _op(
        "dynamodb.list_tags_of_resource",
        "dynamodb",
        "list_tags_of_resource",
        "dynamodb",
        "list-tags-of-resource",
        result_keys=("Tags",),
        paginated=True,
    ),
    _op(
        "ecs.list_task_definitions",
        "ecs",
        "list_task_definitions",
        "ecs",
        "list-task-definitions",
        result_keys=("taskDefinitionArns",),
        paginated=True,
    ),
    _op(
        "ecs.describe_task_definition",
        "ecs",
        "describe_task_definition",
        "ecs",
        "describe-task-definition",
    ),
    _op(
        "ecs.list_clusters",
        "ecs",
        "list_clusters",
        "ecs",
        "list-clusters",
        result_keys=("clusterArns",),
        paginated=True,
    ),
    _op(
        "ecs.list_services",
        "ecs",
        "list_services",
        "ecs",
        "list-services",
        result_keys=("serviceArns",),
        paginated=True,
    ),
    _op(
        "ecs.describe_services",
        "ecs",
        "describe_services",
        "ecs",
        "describe-services",
        result_keys=("services",),
    ),
    _op(
        "ecs.list_tasks",
        "ecs",
        "list_tasks",
        "ecs",
        "list-tasks",
        result_keys=("taskArns",),
        paginated=True,
    ),
    _op(
        "ecs.describe_tasks",
        "ecs",
        "describe_tasks",
        "ecs",
        "describe-tasks",
        result_keys=("tasks",),
    ),
    _op(
        "eks.list_clusters",
        "eks",
        "list_clusters",
        "eks",
        "list-clusters",
        result_keys=("clusters",),
        paginated=True,
    ),
    _op(
        "eks.describe_cluster",
        "eks",
        "describe_cluster",
        "eks",
        "describe-cluster",
        expected_missing_codes=("ResourceNotFoundException",),
    ),
    _op(
        "eks.describe_cluster_versions",
        "eks",
        "describe_cluster_versions",
        "eks",
        "describe-cluster-versions",
        result_keys=("clusterVersions",),
        paginated=True,
    ),
    _op(
        "eks.list_nodegroups",
        "eks",
        "list_nodegroups",
        "eks",
        "list-nodegroups",
        result_keys=("nodegroups",),
        paginated=True,
    ),
    _op(
        "eks.describe_nodegroup",
        "eks",
        "describe_nodegroup",
        "eks",
        "describe-nodegroup",
        expected_missing_codes=("ResourceNotFoundException",),
    ),
    _op(
        "eks.list_addons",
        "eks",
        "list_addons",
        "eks",
        "list-addons",
        result_keys=("addons",),
        paginated=True,
    ),
    _op(
        "eks.describe_addon",
        "eks",
        "describe_addon",
        "eks",
        "describe-addon",
        expected_missing_codes=("ResourceNotFoundException",),
    ),
    _op(
        "eks.describe_addon_versions",
        "eks",
        "describe_addon_versions",
        "eks",
        "describe-addon-versions",
        result_keys=("addons",),
        paginated=True,
    ),
    _op(
        "guardduty.list_detectors",
        "guardduty",
        "list_detectors",
        "guardduty",
        "list-detectors",
        result_keys=("DetectorIds",),
        paginated=True,
    ),
    _op(
        "guardduty.get_detector",
        "guardduty",
        "get_detector",
        "guardduty",
        "get-detector",
        expected_missing_codes=("BadRequestException",),
    ),
    _op(
        "ssm.get_parameter",
        "ssm",
        "get_parameter",
        "ssm",
        "get-parameter",
        expected_missing_codes=("ParameterNotFound",),
    ),
    _op(
        "elbv2.describe_load_balancers",
        "elbv2",
        "describe_load_balancers",
        "elbv2",
        "describe-load-balancers",
        result_keys=("LoadBalancers",),
        paginated=True,
    ),
    _op(
        "elbv2.describe_load_balancer_attributes",
        "elbv2",
        "describe_load_balancer_attributes",
        "elbv2",
        "describe-load-balancer-attributes",
    ),
    _op(
        "elbv2.describe_listeners",
        "elbv2",
        "describe_listeners",
        "elbv2",
        "describe-listeners",
        result_keys=("Listeners",),
        paginated=True,
    ),
    _op(
        "elbv2.describe_listener_certificates",
        "elbv2",
        "describe_listener_certificates",
        "elbv2",
        "describe-listener-certificates",
        result_keys=("Certificates",),
        paginated=True,
    ),
    _op(
        "elbv2.describe_ssl_policies",
        "elbv2",
        "describe_ssl_policies",
        "elbv2",
        "describe-ssl-policies",
        result_keys=("SslPolicies",),
        paginated=True,
    ),
    _op(
        "elbv2.describe_target_groups",
        "elbv2",
        "describe_target_groups",
        "elbv2",
        "describe-target-groups",
        result_keys=("TargetGroups",),
        paginated=True,
    ),
    _op(
        "elbv2.describe_target_health",
        "elbv2",
        "describe_target_health",
        "elbv2",
        "describe-target-health",
    ),
    _op(
        "elbv2.describe_tags",
        "elbv2",
        "describe_tags",
        "elbv2",
        "describe-tags",
        result_keys=("TagDescriptions",),
    ),
    _op("acm.describe_certificate", "acm", "describe_certificate", "acm", "describe-certificate"),
    _op(
        "kms.list_keys",
        "kms",
        "list_keys",
        "kms",
        "list-keys",
        result_keys=("Keys",),
        paginated=True,
    ),
    _op("kms.describe_key", "kms", "describe_key", "kms", "describe-key"),
    _op("kms.get_key_policy", "kms", "get_key_policy", "kms", "get-key-policy"),
    _op(
        "kms.get_key_rotation_status",
        "kms",
        "get_key_rotation_status",
        "kms",
        "get-key-rotation-status",
    ),
    _op(
        "kms.list_resource_tags",
        "kms",
        "list_resource_tags",
        "kms",
        "list-resource-tags",
        result_keys=("Tags",),
        paginated=True,
    ),
    _op(
        "secretsmanager.list_secrets",
        "secretsmanager",
        "list_secrets",
        "secretsmanager",
        "list-secrets",
        result_keys=("SecretList",),
        paginated=True,
    ),
    _op(
        "secretsmanager.describe_secret",
        "secretsmanager",
        "describe_secret",
        "secretsmanager",
        "describe-secret",
    ),
    _op(
        "sns.list_topics",
        "sns",
        "list_topics",
        "sns",
        "list-topics",
        result_keys=("Topics",),
        paginated=True,
    ),
    _op("sns.get_topic_attributes", "sns", "get_topic_attributes", "sns", "get-topic-attributes"),
    _op(
        "sns.list_tags_for_resource",
        "sns",
        "list_tags_for_resource",
        "sns",
        "list-tags-for-resource",
    ),
    _op(
        "sqs.list_queues",
        "sqs",
        "list_queues",
        "sqs",
        "list-queues",
        result_keys=("QueueUrls",),
        paginated=True,
    ),
    _op("sqs.get_queue_attributes", "sqs", "get_queue_attributes", "sqs", "get-queue-attributes"),
    _op("sqs.get_queue_url", "sqs", "get_queue_url", "sqs", "get-queue-url"),
    _op("sqs.list_queue_tags", "sqs", "list_queue_tags", "sqs", "list-queue-tags"),
    _op(
        "apigateway.get_rest_apis",
        "apigateway",
        "get_rest_apis",
        "apigateway",
        "get-rest-apis",
        result_keys=("items",),
        paginated=True,
    ),
    _op(
        "apigateway.get_stages",
        "apigateway",
        "get_stages",
        "apigateway",
        "get-stages",
    ),
    _op(
        "apigateway.get_resources",
        "apigateway",
        "get_resources",
        "apigateway",
        "get-resources",
        result_keys=("items",),
        paginated=True,
    ),
    _op("apigateway.get_method", "apigateway", "get_method", "apigateway", "get-method"),
    _op("apigateway.get_tags", "apigateway", "get_tags", "apigateway", "get-tags"),
    _op(
        "securityhub.get_findings",
        "securityhub",
        "get_findings",
        "securityhub",
        "get-findings",
        result_keys=("Findings",),
        paginated=True,
    ),
    _op(
        "compute-optimizer.get_ec2_instance_recommendations",
        "compute-optimizer",
        "get_ec2_instance_recommendations",
        "compute-optimizer",
        "get-ec2-instance-recommendations",
        result_keys=("instanceRecommendations",),
        paginated=True,
    ),
    _op(
        "compute-optimizer.get_ebs_volume_recommendations",
        "compute-optimizer",
        "get_ebs_volume_recommendations",
        "compute-optimizer",
        "get-ebs-volume-recommendations",
        result_keys=("volumeRecommendations",),
        paginated=True,
    ),
    _op(
        "compute-optimizer.get_lambda_function_recommendations",
        "compute-optimizer",
        "get_lambda_function_recommendations",
        "compute-optimizer",
        "get-lambda-function-recommendations",
        result_keys=("lambdaFunctionRecommendations",),
        paginated=True,
    ),
    _op(
        "cost-optimization-hub.list_recommendations",
        "cost-optimization-hub",
        "list_recommendations",
        "cost-optimization-hub",
        "list-recommendations",
        result_keys=("items",),
        paginated=True,
    ),
)


READ_OPERATIONS: Dict[str, AwsReadOperation] = {
    operation.key: operation for operation in _OPERATIONS
}

IAM_ACTION_OVERRIDES = {
    "s3.list_buckets": "s3:ListAllMyBuckets",
    "s3.get_public_access_block": "s3:GetBucketPublicAccessBlock",
    "s3.get_bucket_encryption": "s3:GetEncryptionConfiguration",
    "s3.get_bucket_lifecycle_configuration": "s3:GetLifecycleConfiguration",
    "s3.get_object_lock_configuration": "s3:GetBucketObjectLockConfiguration",
    "s3.get_bucket_replication": "s3:GetReplicationConfiguration",
    "iam.list_mfa_devices": "iam:ListMFADevices",
    "rds.describe_db_instances": "rds:DescribeDBInstances",
    "rds.describe_db_snapshots": "rds:DescribeDBSnapshots",
    "efs.describe_file_systems": "elasticfilesystem:DescribeFileSystems",
    "efs.describe_lifecycle_configuration": "elasticfilesystem:DescribeLifecycleConfiguration",
    "efs.describe_mount_targets": "elasticfilesystem:DescribeMountTargets",
    "efs.describe_access_points": "elasticfilesystem:DescribeAccessPoints",
    "elbv2.describe_load_balancers": "elasticloadbalancing:DescribeLoadBalancers",
    "elbv2.describe_load_balancer_attributes": "elasticloadbalancing:DescribeLoadBalancerAttributes",
    "elbv2.describe_listeners": "elasticloadbalancing:DescribeListeners",
    "elbv2.describe_listener_certificates": "elasticloadbalancing:DescribeListenerCertificates",
    "elbv2.describe_ssl_policies": "elasticloadbalancing:DescribeSSLPolicies",
    "elbv2.describe_target_groups": "elasticloadbalancing:DescribeTargetGroups",
    "elbv2.describe_target_health": "elasticloadbalancing:DescribeTargetHealth",
    "elbv2.describe_tags": "elasticloadbalancing:DescribeTags",
    "apigateway.get_rest_apis": "apigateway:GET",
    "apigateway.get_stages": "apigateway:GET",
    "apigateway.get_resources": "apigateway:GET",
    "apigateway.get_method": "apigateway:GET",
    "apigateway.get_tags": "apigateway:GET",
    "dynamodb.list_tags_of_resource": "dynamodb:ListTagsOfResource",
    "compute-optimizer.get_ec2_instance_recommendations": "compute-optimizer:GetEC2InstanceRecommendations",
    "compute-optimizer.get_ebs_volume_recommendations": "compute-optimizer:GetEBSVolumeRecommendations",
    "compute-optimizer.get_lambda_function_recommendations": "compute-optimizer:GetLambdaFunctionRecommendations",
    "cost-optimization-hub.list_recommendations": "cost-optimization-hub:ListRecommendations",
}


def read_operation(key: str) -> AwsReadOperation:
    try:
        return READ_OPERATIONS[key]
    except KeyError as exc:
        raise ValueError(f"AWS read operation is not allowlisted: {key}") from exc


def iam_action_for_operation(key: str) -> str:
    """Return the exact IAM action for one allowlisted read capability."""

    read_operation(key)
    if key in IAM_ACTION_OVERRIDES:
        return IAM_ACTION_OVERRIDES[key]
    service, _, api_name = key.partition(".")
    action = "".join(part.capitalize() for part in api_name.split("_"))
    return f"{service}:{action}"
